#!/bin/csh
set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2`

@ ifile = 1
@ navgfile = 10
@ inextfile = $ifile + $navgfile - 1
@ igenfile = 1
while ( -e $inextfile )
  mv $ifile struct1
  @ ifile = $ifile + 1
  mv $ifile struct2
  @ ifile = $ifile + 1
  mv $ifile struct3
  @ ifile = $ifile + 1
  mv $ifile struct4
  @ ifile = $ifile + 1
  mv $ifile struct5
  @ ifile = $ifile + 1
  mv $ifile struct6
  @ ifile = $ifile + 1
  mv $ifile struct7
  @ ifile = $ifile + 1
  mv $ifile struct8
  @ ifile = $ifile + 1
  mv $ifile struct9
  @ ifile = $ifile + 1
  mv $ifile struct10
  $sluschipath/avg.x
  cat avg >> $igenfile
  @ igenfile = $igenfile + 1
  @ ifile = $ifile + 1
  @ inextfile = $ifile + $navgfile - 1
end
