#!/bin/bash
#SBATCH -J SLUSCHI        # Job Name
#SBATCH -o SLUSCHI.o%j    # Output and error file name (%j expands to jobID)
#SBATCH -n 16           # Total number of mpi tasks requested
#SBATCH -p serial # Queue (partition) name -- normal, development, etc.
#SBATCH -t 4:00:00     # Run time (hh:mm:ss) - 1.5 hours


autojob_LongWT > log.out 
