#!/bin/csh

cd ..
cp INCAR POSCAR POTCAR jobsub job.in Dir_OptUnitCell
cp KPOINTS_OPT Dir_OptUnitCell/KPOINTS
cd Dir_OptUnitCell

set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2`
set vaspcmd = `getinfo.csh vaspcmd job.in`
set pstress = `getinfo.csh press job.in`

# INCAR
sed -i '/NBANDS/d' INCAR
$sluschipath/UpdateINCAR PREC high
set temp = `getinfo.csh temp job.in`
set sigma = `awk -v a="0.000086" -v b=$temp 'BEGIN{print (b*a)}'`
$sluschipath/UpdateINCAR SIGMA $sigma
$sluschipath/UpdateINCAR ISMEAR -1
$sluschipath/UpdateINCAR IBRION 2
$sluschipath/UpdateINCAR ISIF 3
$sluschipath/UpdateINCAR POTIM 0.1
$sluschipath/UpdateINCAR NSW 40
$sluschipath/UpdateINCAR PSTRESS $pstress
sed -i '/SMASS/d' INCAR
sed -i '/TEBEG/d' INCAR
sed -i '/TEEND/d' INCAR
sed -i '/ISYM/d' INCAR

#submit job
$vaspcmd jobsub >> jobsub.log

@ stopflag = 0
while ($stopflag == 0)
  sleep 60 ############################################################
  if ( -e OUTCAR ) then
    grep -s "Total CPU" OUTCAR > /dev/null
    if (! $?) @ stopflag = 1
  endif
end

cp CONTCAR POSCAR
rm OUTCAR WAVECAR CHG*
$vaspcmd jobsub >> jobsub.log

@ stopflag = 0
while ($stopflag == 0)
  sleep 60 ############################################################
  if ( -e OUTCAR ) then
    grep -s "Total CPU" OUTCAR > /dev/null
    if (! $?) @ stopflag = 1 
  endif
end

touch optunitcell_is_done
cp CONTCAR ../POSCAR
