#!/bin/csh
 
#SBATCH -J mds_master       # name                                              
#SBATCH -p general       # partition                                         
#SBATCH -q public      # QOS                                                
#SBATCH -N 1  # number of nodes
#SBATCH -n 1  # number of "tasks" (default: allocates 1 core per task)
#SBATCH -t 7-0:00:00   # time in d-hh:mm:ss
#SBATCH -o slurm.%j.out # file to save job's STDOUT (%j = JobId)
#SBATCH -e slurm.%j.err # file to save job's STDERR (%j = JobId)
#SBATCH --mail-type=ALL # Send an e-mail when a job starts, stops, or fails
#SBATCH --mail-user=%u@asu.edu # Mail-to address
##SBATCH --export=NONE   # Purge the job-submitting shell environment
##SBATCH --nodelist=cg45-2
#SBATCH --mem=8G

module load matlab

set filename = replace_here
echo $filename

cp latt latt_$filename
cp step step_$filename
cp param param_$filename
cp pos pos_$filename

matlab -r "run('main.m'); exit;" > entropy.out
