#!/bin/bash
 
#SBATCH -J mds_master       # name                                              
#SBATCH -p general       # partition                                         
#SBATCH -q grp_qhong7       # QOS                                                
#SBATCH -N 1  # number of nodes
#SBATCH -n 3  # number of "tasks" (default: allocates 1 core per task)
#SBATCH -t 7-0:00:00   # time in d-hh:mm:ss
#SBATCH -o slurm.%j.out # file to save job's STDOUT (%j = JobId)
#SBATCH -e slurm.%j.err # file to save job's STDERR (%j = JobId)
#SBATCH --mail-type=ALL # Send an e-mail when a job starts, stops, or fails
#SBATCH --mail-user=%u@asu.edu # Mail-to address
##SBATCH --export=NONE   # Purge the job-submitting shell environment
#SBATCH --nodelist=scc005
#SBATCH --mem=12G

/data/qhong7/qhong7/sluschi/sluschi_latest/src/mds_lmp > log.out &                                           

sleep 3600000
