#!/bin/csh
set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2`

getinfo.csh diff_solid ../../job.in > /dev/null
if ( $? == 0 ) then
  getinfo.csh diff_solid ../../job.in > diff.in
else
  echo 0.5 > diff.in
endif
getinfo.csh diff_liquid ../../job.in > /dev/null
if ( $? == 0 ) then
  getinfo.csh diff_liquid ../../job.in >> diff.in
else
  echo 1.0 >> diff.in
endif
getinfo.csh diff_select ../../job.in > /dev/null
if ( $? == 0 ) then
  getinfo.csh diff_select ../../job.in >> diff.in
else
  echo -1 >> diff.in
endif
grep '^Direct$' ../../CONTCAR -B1 | grep -v Direct > natoms
cp ../../../../../stop_info.in .
sleep 5


@ iter = 1
while ( -e ../../$iter )
  @ iter = $iter + 1
end
@ iter = $iter - 1
set potim = `grep 'POTIM  =' ../../$iter/OUTCAR | awk '{print $3}'`
echo $potim > potim

tail -1 ../../OSZICAR | awk '{print $7}' > energy.out 
$sluschipath/avg_anal
rm diff_his avghalf_his
touch diff_his avghalf_his
@ ifile = 1
@ inextfile = $ifile + 1
while ( -e $inextfile  )
  cp $ifile struct0
  cp $inextfile struct1
  while ( ! -e diff.in )
    sleep 10
  end
  $sluschipath/diff.x
  cat diff >> diff_his
  cat avghalf >> avghalf_his
  @ ifile = $inextfile
  @ inextfile = $ifile + 1
end
@ flag_homo = `cat flag_homo`
if ( $flag_homo == 1 ) then
#  @ ifile = $ifile - 1
  echo $ifile > iter_homo
endif
