#!/bin/csh
set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2`

@ iter = 1
while ( -e ../../$iter )
  @ iter = $iter + 1
end
@ iter = $iter - 1
set potim = `grep 'POTIM  =' ../../$iter/OUTCAR | awk '{print $3}'`
echo $potim > potim

tail -1 ../../OSZICAR | awk '{print $7}' > energy.out 
$sluschipath/avg_anal
rm diff_his avghalf_his
touch diff_his avghalf_his
@ ifile = 1
@ inextfile = $ifile + 1
while ( -e $inextfile  )
  cp $ifile struct0
  cp $inextfile struct1
  while ( ! -e diff.in )
    sleep 10
  end
  $sluschipath/diff.x
  cat diff >> diff_his
  cat avghalf >> avghalf_his
  @ ifile = $inextfile
  @ inextfile = $ifile + 1
end
@ flag_homo = `cat flag_homo`
if ( $flag_homo == 1 ) then
#  @ ifile = $ifile - 1
  echo $ifile > iter_homo
endif
