#!/bin/csh
cp ../job.in .
set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2`

@ FlagStop = 0
echo $FlagStop > FlagStop.out
@ FlagFit = 0
if ( -e job_results.out ) then
  rm jobs_to_run.out
else
  set temp = `getinfo.csh temp job.in`
  echo $temp 1 > jobs_to_run.out
endif
getinfo.csh confident job.in > confident.in
getinfo.csh error job.in > ErrorTarget.in
cd ../Dir_CoexRun

while ( $FlagStop == 0 )

  # submit jobs following jobs_to_run.out
  if ( -e jobs_to_run.out ) then
    cp jobs_to_run.out jobs_to_run.out_tmp
    @ l = `cat jobs_to_run.out_tmp | wc -l`
    while ( $l > 0 )
      @ temp = `head -1 jobs_to_run.out_tmp | awk '{print $1}' | cut -d'.' -f1`
      @ n = `head -1 jobs_to_run.out_tmp | awk '{print $2}'`
      if ( -d $temp ) then
        @ n0 = `cat $temp/$temp/iters_to_finish`
      else
        @ n0 = 0
      endif
      if ( $n > $n0 ) $sluschipath/StartJob-longMD $temp $n
      sed -i '1d' jobs_to_run.out_tmp
      @ l = `cat jobs_to_run.out_tmp | wc -l`
    end
    touch Coex_MD_is_running
  endif


#///////////lw lw lw//////////////////////////

      $sluschipath/StopJob.x >> ../SLUSCHI.out
       @ FlagStop = `cat FlagStop.out`   
          
#   set pwd = `pwd`                                                                 
#   echo \*\*\* I am in coexrun $pwd \*\*\* >> ../SLUSCHI.out   

end
