#!/bin/csh
set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2`
set vaspcmd = `getinfo.csh vaspcmd job.in`

if ( -d Dir_Converge ) rm -r Dir_Converge

mkdir Dir_Converge
cp INCAR KPOINTS CONTCAR POTCAR jobsub Dir_Converge
cd Dir_Converge
mv CONTCAR POSCAR
mkdir normal high
cp INCAR KPOINTS POSCAR POTCAR jobsub normal
cd normal

$sluschipath/UpdateINCAR IBRION -1
$sluschipath/UpdateINCAR NSW 1
$vaspcmd jobsub >> jobsub.log

@ jobdone = 0
while ( ! $jobdone )
  sleep 30

  if ( -e OUTCAR ) then
    grep -s "Total CPU" OUTCAR > /dev/null
    if (! $?) then # Job is done
      @ jobdone = 1
      set P_normal = `grep pressure OUTCAR | grep Pullay | awk '{print $4}'`
      set E_normal = `grep 'energy  without entropy' OUTCAR  | tail -1 | awk '{print $4}'`
    endif
  endif
end

cp * ../high
cd ../high
$sluschipath/UpdateINCAR PREC high
sed -i '/ENCUT/d' INCAR
# Generate KPOINTS file twice denser
set kmesh = `getinfo.csh kmesh ../../job.in`
@ kmesh = $kmesh + $kmesh
cat - << EOF > KPOINTS
KPOINTS by SLUSCHI
0
Auto
$kmesh
EOF

$vaspcmd jobsub >> jobsub.log
rm OUTCAR

@ jobdone = 0
while ( ! $jobdone )
  sleep 30

  if ( -e OUTCAR ) then
    grep -s "Total CPU" OUTCAR > /dev/null
    if (! $?) then # Job is done
      @ jobdone = 1
      set P_high = `grep pressure OUTCAR | grep Pullay | awk '{print $4}'`
      set E_high = `grep 'energy  without entropy' OUTCAR  | tail -1 | awk '{print $4}'`
    endif
  endif
end
@ natom = `grep 'NIONS =' OUTCAR | tail -1 | awk '{print $12}'`

cd ../..
set P_normal_minus = `awk 'BEGIN{print '$P_normal'*-1}'`
awk 'BEGIN{print '$P_high'+'$P_normal_minus'}' > pressure_converge.out
set E_normal_minus = `awk 'BEGIN{print '$E_normal'*-1}'`
awk 'BEGIN{print ('$E_high'+'$E_normal_minus')/'$natom'}' > energy_converge.out
