#!/bin/csh

set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2`
set vaspcmd = `getinfo.csh vaspcmd job.in`

@ temp_now = $1
@ n_iter = $2 # n_iter must be 2^n, n is interger and n=[0,5]

if ( ! -d $temp_now ) then
  mkdir $temp_now
  mkdir $temp_now/$temp_now
  cd ..
  cp -r src_coex/ Dir_CoexRun/$temp_now/ # delete?
  cd Dir_Melt
  cp POSCAR POTCAR OUTCAR POSCAR_coex_head ../Dir_CoexRun/$temp_now/src_coex
  cd ..
  cp INCAR KPOINTS jobsub job.in Dir_CoexRun/$temp_now/src_coex
  if ( -e jobsub_gamma ) cp jobsub_gamma Dir_CoexRun/$temp_now/src_coex
  if ( -e KPOINTS_gamma ) cp KPOINTS_gamma Dir_CoexRun/$temp_now/src_coex
  cd Dir_CoexRun/$temp_now/src_coex
  $sluschipath/UpdateINCAR NSW 80
  $sluschipath/UpdateINCAR SMASS 0
  set sigma = `awk -v a="0.000086" -v b=$temp_now 'BEGIN{print (b*a)}'`
  $sluschipath/UpdateINCAR SIGMA $sigma
  $sluschipath/UpdateINCAR TEBEG $temp_now
  $sluschipath/UpdateINCAR TEEND $temp_now
#  $sluschipath/UpdateINCAR PREC normal
  cd ../..
endif
cd $temp_now/$temp_now
echo $n_iter > iters_to_finish
echo === Run NPT MD at $temp_now K on $n_iter snapshot"("s")" === >> ../../../SLUSCHI.out

# capture structures
@ snap_done = 0
@ snap_end = `cat iters_to_finish`
@ iter_now = 0
@ iter_long = 4000  # total 5000
@ iter_step = `awk 'BEGIN{print '$iter_long'/'$snap_end'}'`

while ($snap_done < $snap_end)
  @ snap_done = $snap_done + 1
  @ iter_now = $iter_now + $iter_step
  if ( -d $iter_now ) then
  else
    cd ../src_coex
    echo $iter_now > iteration 
    @ pos_found = 0
    while ($pos_found == 0)
      @ natom = `grep 'NIONS =' OUTCAR | tail -1 | awk '{print $12}'`
      echo $natom > natom
      $sluschipath/GetPos.x
      @ flag_getpos = `cat get_pos_success`
      if ($flag_getpos) then
        mkdir ../$temp_now/$iter_now
        cp position ../$temp_now/$iter_now
        cd ../src_coex
        cp -r * ../$temp_now/$iter_now
        cd ../$temp_now/$iter_now
        cat position | awk '{print $3,$4,$5}' | head -$natom > POS
        rm position
        if ( ! -e ../POSCAR_head ) then
          cat ../../src_coex/POSCAR_coex_head > POSCAR
          echo Cartisian >> POSCAR
          cat POS >> POSCAR
          cd ..
          mkdir Dir_VolSearchCoex
          cp $iter_now/* Dir_VolSearchCoex
          cd Dir_VolSearchCoex
          rm OUTCAR
          $sluschipath/volsearch_coex > log.out
          head -6 POSCAR > ../POSCAR_head
          cd ../$iter_now
        endif
        cat ../POSCAR_head > POSCAR
        echo Cartisian >> POSCAR
        cat POS >> POSCAR
        echo $iter_now > snapnum
        echo --- RUNNING at $temp_now K for snapshot ID $iter_now --- >> ../../../../SLUSCHI.out
        echo --- READ Dir_CoexRun/$temp_now/$temp_now/$iter_now/log.out FOR DETAILS --- >> ../../../../SLUSCHI.out
        rm OUTCAR
        @ LongWT = 0
        getinfo.csh LongWT job.in > /dev/null
        if ( $? == 0 ) then
          set LongWT = `getinfo.csh LongWT job.in`
        endif 
        getinfo.csh mlff job.in > /dev/null                                             
        if ( $? == 0 ) then                                                             
          @ mlff = `getinfo.csh mlff job.in`                                            
        else                                                                            
          @ mlff = 0                                                                    
        endif                                                                           
        if ( $LongWT == 0 ) then
          if ( $mlff == 1 ) then
            $sluschipath/autojob_ml > log.out &
          else
            $sluschipath/autojob > log.out &
          endif
        else
          cp ../../../../jobsub_LongWT .
          $vaspcmd jobsub_LongWT
        endif
        cd ../
        @ pos_found = 1
      else
        sleep 600
      endif
    end
  endif
  sleep 60
end
